title: 권재준의 포트폴리오
description: 발전하는 개발자가 되고 싶습니다 
site_title: 'Portfolio Kwon Jae-Jun'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: alikwon
blog_url: https://blog.naver.com/rnjswownskj
email: wownskl@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 