title: 권재준의 포트폴리오
description: Web & Security Engineer
site_title: 'portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: alikwon
blog_url: https://blog.naver.com/rnjswownskj
email: wownskl@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 